// Generated by gencpp from file create_fundamentals/Leds.msg
// DO NOT EDIT!


#ifndef CREATE_FUNDAMENTALS_MESSAGE_LEDS_H
#define CREATE_FUNDAMENTALS_MESSAGE_LEDS_H

#include <ros/service_traits.h>


#include <create_fundamentals/LedsRequest.h>
#include <create_fundamentals/LedsResponse.h>


namespace create_fundamentals
{

struct Leds
{

typedef LedsRequest Request;
typedef LedsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Leds
} // namespace create_fundamentals


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::create_fundamentals::Leds > {
  static const char* value()
  {
    return "926a8fe91d451f4d4bb099ec9e86ff14";
  }

  static const char* value(const ::create_fundamentals::Leds&) { return value(); }
};

template<>
struct DataType< ::create_fundamentals::Leds > {
  static const char* value()
  {
    return "create_fundamentals/Leds";
  }

  static const char* value(const ::create_fundamentals::Leds&) { return value(); }
};


// service_traits::MD5Sum< ::create_fundamentals::LedsRequest> should match 
// service_traits::MD5Sum< ::create_fundamentals::Leds > 
template<>
struct MD5Sum< ::create_fundamentals::LedsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::create_fundamentals::Leds >::value();
  }
  static const char* value(const ::create_fundamentals::LedsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::create_fundamentals::LedsRequest> should match 
// service_traits::DataType< ::create_fundamentals::Leds > 
template<>
struct DataType< ::create_fundamentals::LedsRequest>
{
  static const char* value()
  {
    return DataType< ::create_fundamentals::Leds >::value();
  }
  static const char* value(const ::create_fundamentals::LedsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::create_fundamentals::LedsResponse> should match 
// service_traits::MD5Sum< ::create_fundamentals::Leds > 
template<>
struct MD5Sum< ::create_fundamentals::LedsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::create_fundamentals::Leds >::value();
  }
  static const char* value(const ::create_fundamentals::LedsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::create_fundamentals::LedsResponse> should match 
// service_traits::DataType< ::create_fundamentals::Leds > 
template<>
struct DataType< ::create_fundamentals::LedsResponse>
{
  static const char* value()
  {
    return DataType< ::create_fundamentals::Leds >::value();
  }
  static const char* value(const ::create_fundamentals::LedsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CREATE_FUNDAMENTALS_MESSAGE_LEDS_H
