// Generated by gencpp from file create_fundamentals/ResetEncoders.msg
// DO NOT EDIT!


#ifndef CREATE_FUNDAMENTALS_MESSAGE_RESETENCODERS_H
#define CREATE_FUNDAMENTALS_MESSAGE_RESETENCODERS_H

#include <ros/service_traits.h>


#include <create_fundamentals/ResetEncodersRequest.h>
#include <create_fundamentals/ResetEncodersResponse.h>


namespace create_fundamentals
{

struct ResetEncoders
{

typedef ResetEncodersRequest Request;
typedef ResetEncodersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetEncoders
} // namespace create_fundamentals


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::create_fundamentals::ResetEncoders > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::create_fundamentals::ResetEncoders&) { return value(); }
};

template<>
struct DataType< ::create_fundamentals::ResetEncoders > {
  static const char* value()
  {
    return "create_fundamentals/ResetEncoders";
  }

  static const char* value(const ::create_fundamentals::ResetEncoders&) { return value(); }
};


// service_traits::MD5Sum< ::create_fundamentals::ResetEncodersRequest> should match 
// service_traits::MD5Sum< ::create_fundamentals::ResetEncoders > 
template<>
struct MD5Sum< ::create_fundamentals::ResetEncodersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::create_fundamentals::ResetEncoders >::value();
  }
  static const char* value(const ::create_fundamentals::ResetEncodersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::create_fundamentals::ResetEncodersRequest> should match 
// service_traits::DataType< ::create_fundamentals::ResetEncoders > 
template<>
struct DataType< ::create_fundamentals::ResetEncodersRequest>
{
  static const char* value()
  {
    return DataType< ::create_fundamentals::ResetEncoders >::value();
  }
  static const char* value(const ::create_fundamentals::ResetEncodersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::create_fundamentals::ResetEncodersResponse> should match 
// service_traits::MD5Sum< ::create_fundamentals::ResetEncoders > 
template<>
struct MD5Sum< ::create_fundamentals::ResetEncodersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::create_fundamentals::ResetEncoders >::value();
  }
  static const char* value(const ::create_fundamentals::ResetEncodersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::create_fundamentals::ResetEncodersResponse> should match 
// service_traits::DataType< ::create_fundamentals::ResetEncoders > 
template<>
struct DataType< ::create_fundamentals::ResetEncodersResponse>
{
  static const char* value()
  {
    return DataType< ::create_fundamentals::ResetEncoders >::value();
  }
  static const char* value(const ::create_fundamentals::ResetEncodersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CREATE_FUNDAMENTALS_MESSAGE_RESETENCODERS_H
