// Generated by gencpp from file create_fundamentals/StoreSong.msg
// DO NOT EDIT!


#ifndef CREATE_FUNDAMENTALS_MESSAGE_STORESONG_H
#define CREATE_FUNDAMENTALS_MESSAGE_STORESONG_H

#include <ros/service_traits.h>


#include <create_fundamentals/StoreSongRequest.h>
#include <create_fundamentals/StoreSongResponse.h>


namespace create_fundamentals
{

struct StoreSong
{

typedef StoreSongRequest Request;
typedef StoreSongResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StoreSong
} // namespace create_fundamentals


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::create_fundamentals::StoreSong > {
  static const char* value()
  {
    return "1368a608865444cc82f73518170a4f78";
  }

  static const char* value(const ::create_fundamentals::StoreSong&) { return value(); }
};

template<>
struct DataType< ::create_fundamentals::StoreSong > {
  static const char* value()
  {
    return "create_fundamentals/StoreSong";
  }

  static const char* value(const ::create_fundamentals::StoreSong&) { return value(); }
};


// service_traits::MD5Sum< ::create_fundamentals::StoreSongRequest> should match 
// service_traits::MD5Sum< ::create_fundamentals::StoreSong > 
template<>
struct MD5Sum< ::create_fundamentals::StoreSongRequest>
{
  static const char* value()
  {
    return MD5Sum< ::create_fundamentals::StoreSong >::value();
  }
  static const char* value(const ::create_fundamentals::StoreSongRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::create_fundamentals::StoreSongRequest> should match 
// service_traits::DataType< ::create_fundamentals::StoreSong > 
template<>
struct DataType< ::create_fundamentals::StoreSongRequest>
{
  static const char* value()
  {
    return DataType< ::create_fundamentals::StoreSong >::value();
  }
  static const char* value(const ::create_fundamentals::StoreSongRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::create_fundamentals::StoreSongResponse> should match 
// service_traits::MD5Sum< ::create_fundamentals::StoreSong > 
template<>
struct MD5Sum< ::create_fundamentals::StoreSongResponse>
{
  static const char* value()
  {
    return MD5Sum< ::create_fundamentals::StoreSong >::value();
  }
  static const char* value(const ::create_fundamentals::StoreSongResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::create_fundamentals::StoreSongResponse> should match 
// service_traits::DataType< ::create_fundamentals::StoreSong > 
template<>
struct DataType< ::create_fundamentals::StoreSongResponse>
{
  static const char* value()
  {
    return DataType< ::create_fundamentals::StoreSong >::value();
  }
  static const char* value(const ::create_fundamentals::StoreSongResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CREATE_FUNDAMENTALS_MESSAGE_STORESONG_H
